name: Copy Files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Check Env
      run: |
        echo $PSversionTable
        pwd
        Get-ChildItem -Path Env:

